version: "3"
services:
  journal:
    container_name: journal
    image: registry.gitlab.com/jaconil/journal:v2.2.1
    restart: always
    ports:
      - 1337:1337
    env_file:
      - .env
